version: 2

vars:
  init: &init
    environment:
        TZ: 'Asia/Taipei'
    docker:
      - image: circleci/node

  save_node_modules:  &save_node_modules
    save_cache:
      key: node_modules#{{ checksum "package-lock.json" }}
      paths:
        - node_modules

  restore_node_modules:  &restore_node_modules
    restore_cache:
      key: node_modules#{{ checksum "package-lock.json" }}

  save_build:  &save_build
    save_cache:
      key: out#{{ .Revision }}
      paths:
        - out

  restore_build:  &restore_build
    restore_cache:
      key: out#{{ .Revision }}

  branch_not_deploy: &branch_not_deploy
    filters:
      branches:
        ignore:
          - master

  branch_is_deploy: &branch_is_deploy
    filters:
      branches:
        only:
          - master

  setup_docker: &setup_docker
    setup_remote_docker:
      docker_layer_caching: true

  setup_npm: &setup_npm
    run:
      name: Setup NPM
      command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

  setup_git: &setup_git
    run:
      name: Setup Git
      command: |
        git config --global user.name "CircleCI"
        git config --global user.email "auto_deploy@circleci.com"

  export_env: &export_env
    run:
      name: Export Env
      command: |
        echo 'export IMAGE=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1' >> $BASH_ENV
        echo 'export GIT_TAG=v$(cat package.json | grep version | cut -d '\''"'\'' -f4)' >> $BASH_ENV

        source $BASH_ENV

        echo $IMAGE
        echo $GIT_TAG

  push_coverage: &push_coverage
    run: curl -s https://codecov.io/bash | bash

jobs:
  lint:
    <<: *init
    steps:
      - checkout
      - *restore_node_modules
      - run: npm i
      - *save_node_modules
      - run: npm run lint

  test:
    <<: *init
    steps:
      - checkout
      - *restore_node_modules
      - run: npm i
      - *save_node_modules
      - run: npm test
      - *push_coverage

  build:
    <<: *init
    steps:
      - checkout
      - *restore_node_modules
      - run: npm i
      - *save_node_modules
      - run: npm run build
      - *save_build

  npm publish:
    <<: *init
    steps:
      - checkout
      - *restore_node_modules
      - run: npm i
      - *save_node_modules
      - *restore_build
      - *setup_npm
      - run: npm publish out

  github tags:
      <<: *init
      steps:
        - checkout
        - *setup_git
        - *export_env
        - run: git tag $GIT_TAG
        - run: git push https://$GH_TOKEN@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git --tags

workflows:
  version: 2
  Testing:
    jobs:
      - lint:
          <<: *branch_not_deploy
      - test:
          <<: *branch_not_deploy
      - build:
          <<: *branch_not_deploy
  Deploying:
    jobs:
      - test:
          <<: *branch_is_deploy
      - build:
          <<: *branch_is_deploy
      - github tags:
          <<: *branch_is_deploy
          requires:
              - test
              - build
      - npm publish:
          <<: *branch_is_deploy
          requires:
              - test
              - build
